# Generated by Django 3.2 on 2021-09-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, to='crm.Contact'),
        ),
        migrations.AlterField(
            model_name='event',
            name='users',
            field=models.ManyToManyField(blank=True, to='crm.UserProfile'),
        ),
        migrations.AlterField(
            model_name='group',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='crm.Contact'),
        ),
    ]
