# Generated by Django 3.2 on 2021-09-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_contact_starred'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='whenAdded',
            field=models.DateTimeField(auto_now_add=True, verbose_name='When Added'),
        ),
    ]
