# Generated by Django 3.2 on 2021-09-11 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_contact_whenadded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='emailAddress',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='lastName',
        ),
    ]
