# Generated by Django 3.2 on 2021-09-12 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20210912_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contactOwner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.userprofile'),
        ),
    ]
