# Generated by Django 3.2.6 on 2021-09-27 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0010_rename_name_userprofilefield_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilefield',
            name='userAccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
